---
- name: Get machine id
  shell: "cat .vagrant/machines/default/virtualbox/index_uuid"
  register: uuid
  args:
    chdir: "{{ vd.dest }}"
  become_user: "{{ vd_vagrant_user }}"
  when: "vd.state is not defined or vd.state == 'up'"

- name: Get machine ssh port
  shell: "vagrant port --guest 22"
  register: port
  args:
    chdir: "{{ vd.dest }}"
  become_user: "{{ vd_vagrant_user }}"
  when: "vd.state is not defined or vd.state == 'up'"

- name: Generating id file
  shell: "echo {{ uuid.stdout }} > .vd_id"
  args:
    chdir: "{{ vd.dest }}"
  become_user: "{{ vd_vagrant_user }}"
  when: "vd.state is not defined or vd.state == 'up'"

- name: Generating summary file
  shell: "echo \"{{ vd.dest }};{{ uuid.stdout }};{{ port.stdout }}\" > .vd_summary"
  args:
    chdir: "{{ vd.dest }}"
  become_user: "{{ vd_vagrant_user }}"
  when: "vd.state is not defined or vd.state == 'up'"

- name: Generating SSH config
  template:
    src: "ssh_config.j2"
    dest: "{{ vd.dest }}/.vd_ssh_config"
    owner: "{{ vd_vagrant_user }}"
  become_user: "{{ vd_vagrant_user }}"
  when: "vd.state is not defined or vd.state == 'up'"
